### ISSUE TITLE
Cannot find valid target when multiple drop types are specified

### ISSUE THREAD

**Issue by Andreyco** [gaearon/react-dnd#296]
I found very interesting bug.

If I specify types for drop target in this way, it works as you'd expect:
```javascript
@DropTarget(['available', 'visible'], groupTarget, connect => ({
    connectDropTarget: connect.dropTarget(),
}))
export default class Group {
    ...
}
```

Since I need to set those types dynamically, I'd like to use function for that. According to docs, it should work - but it doesn't
```javascript
const dropTypes = props => props.accept;

@DropTarget(dropTypes, groupTarget, connect => ({
    connectDropTarget: connect.dropTarget(),
}))
export default class Group {
    ...
}
```

Btw, it works if I return string from function.

**Comment by gaearon** [comment]
This is what drop targets in `Dustbin / Multiple Targets` example [do](https://github.com/gaearon/react-dnd/blob/2bdcbfc03935693b0ec1d279726efb7250ccc7c3/examples/01%20Dustbin/Multiple%20Targets/Dustbin.js#L23), and they definitely [receive arrays](https://github.com/gaearon/react-dnd/blob/2bdcbfc03935693b0ec1d279726efb7250ccc7c3/examples/01%20Dustbin/Multiple%20Targets/Container.js#L15-L18).

Are you sure `props.accept` is an array of strings? Can you create a sample project reproducing this behavior?

**Comment by gaearon** [comment]
I'm closing. If you can provide a reproducing example, I will gladly reopen.

**Comment by TuiKiken** [comment]
@gaearon, look at [this line](https://github.com/gaearon/react-dnd/blob/2bdcbfc03935693b0ec1d279726efb7250ccc7c3/examples/04%20Sortable/Simple/Card.js#L61).
You can reproduce bug if you just change the line to `@DropTarget((props) => ([ItemTypes.CARD])`

**Comment by gaearon** [comment]
Would you like to investigate why this happens?

**Comment by TuiKiken** [comment]
@gaearon i'll try.

**Comment by TuiKiken** [comment]
@gaearon take a look at [this line](https://github.com/gaearon/react-dnd/blob/master/src/decorateHandler.js#L88). In my case comparison failed because array compares by reference rather than value. Although the types are not changed occurs initialization below and takes some time. At this time the browser emit events and [performs handler](https://github.com/gaearon/react-dnd-html5-backend/blob/master/src/HTML5Backend.js#L52) that [uses variable](https://github.com/gaearon/dnd-core/blob/master/src/HandlerRegistry.js#L112) not initialized yet. BANG!

Maybe will be better assign array to `this.currentType`, initialize [this code](https://github.com/gaearon/react-dnd/blob/master/src/decorateHandler.js#L94-L125) once with `this.currentType` instead of `type` and every `receiveType(type)` call just work with `this.currentType` array. Something like that:
``` javascript
receiveType(type) {
  // maybe some check here
  this.currentType.length = 0;
  if (type instanceof Array) {
    type.forEach(x => this.currentType.push(x));
  } else {
    this.currentType.push(type)
  }
}
```
In this case – acceptable types will be changed immediately by reference without reinitializing. I haven't delved deep into the project so this solution may not work in all cases but works for current case.

**Comment by TuiKiken** [comment]
Or just describe this case in the documentation.

**Comment by gaearon** [comment]
I might have some time right after Christmas so I'm hoping to take a closer look at that.
Thanks for your help with finding the issue.

**Comment by gaearon** [comment]
Fixed in dnd-core via gaearon/dnd-core@f1893a6.

**Comment by gaearon** [comment]
This is probably fixed in 2.1.0.
I’ll close but please let me know if not, and I’ll reopen.

**Comment by oadeojo** [comment]
@gaearon 
```
DropTarget((props) => ([ItemTypes.CARD]), spec, collect)
```
is still failing. I am not able to return multiple types when using a function.
I am using `v2.5.1`
